version: '3.9'
services:
  app:
    build: ./php
    ports:
      - ${HTTP_PORT_HOST}:80
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./php/apache:/etc/apache2/sites-available
      - ../src/logs:/var/log/apache2
#   db:
#     build: ./postgres
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     ports:
#       - ${POSTGRES_DB_PORT}:5434
#     command: -p 5434
#     environment:
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_USER: ${POSTGRES_USER}

# volumes:
#   db-data: